### ISSUE TITLE
تغییر آدرس پرداخت بانک ملت

### ISSUE THREAD

**Issue by mohsen2hasani** [odises/nopCommercePlugins#12]
سلام
با توجه به عوض شدن آدرس به پرداخت، باید در app.config
مقدار 
https://pgws.bpm.bankmellat.ir/pgwchannel/services/pgw
به 
https://bpm.shaparak.ir/pgwchannel/services/pgw?wsdl
تغییر کند 

BeforeGateway.cshtml و همینطور در 
https://pgw.bpm.bankmellat.ir/pgwchannel/startpay.mellat
به 
https://bpm.shaparak.ir/pgwchannel/startpay.mellat
تغییر کند.

روز بخیر

**Comment by odises** [comment]
Hi, thank you for your report.
Could you please make a pull request? @mohsenelf

**Comment by odises** [comment]
resolved by #13 and #14
