### ISSUE TITLE
New Version 3.90

### ISSUE THREAD

**Issue by hitaspdotnet** [odises/nopCommercePlugins#17]
سلام 
خیلی خیلی خیلی ممنونم از اشتراک گذاری
برای  نصب روی ورژن جدید nopCommerce چکار باید انجام بدم؟
برای استفاده از پلاگین شما مجبور شدم ورژن 3.8 رو نصب کنم که متاسفانه باعث شد یه تعداد پلاگین که هزینه کرده بودم رو از دست بدم
می شه لطف کنید راهنماییم کنید؟ 
سورس رو که اجرا میکنم تغییرات لازم برای هماهنگ سازی رو انجام میدم (در حد خطاهای ویژوال استدیو) اما موقع نصب بر روی CMS کلی خطا میده

**Comment by odises** [comment]
با سلام
آیا موفق به راه‌اندازی پلاگین پرداخت، بر روی نسخه ۳.۸ شده‌اید؟
[این](http://docs.nopcommerce.com/display/en/How+to+write+a+nopCommerce+plugin) داکیومنت می‌تواند به شما کمک کند.
در صورتی که مشکل حل نشد، خطاها را دقیق‌تر بیان نمایید.
با تشکر

**Comment by hitaspdotnet** [comment]
سلام مجدد. 
موضوع اول بله روی ورژن 3.8 نصب کردم پرداخت هم انجام شد تمام گزارشات مرحله به مرحله خرید بی نقص اجرا شد به جز اینکه اگر مشتری در دروازه پرداخت انصراف بزند در هنگام بازگشت به سایت باید محصول بعنوان پرداخت نشده توی سبد خرید بماند اما حذف میشود و فقط در پنل ادمین برچسب Pending میگیرد
این ضعف زمانی مشخص میشود که مشتری بخواهد دوباره همان خرید را تکرار کند چون 1 درخواست در سبد خرید خود میبیند اما در جمع بندی کل فاکتور پرداخت نشده قبلی هم محاسبه میشود.
البته با ایجاد یه تسک تونستم تمام سفارشات معلق را هر 15 دقیقه پاک کنم و مشکل حل شد.

**Comment by hitaspdotnet** [comment]
موضوع دوم روی ورژن 3.9 موقع دیباگ کد چندتا خطای ساده میده از جمله OrderDescription که باید توی متد PaymentMethod  باشه اما توی ورژن 3.8 نیاز نبود. اما بعد از دیباگ خروجی رو توی فلودر پلاگین که میذارم توی لیست لوکال پلاگین میاد ولی نصب نمیشه بعد از زدن کلید نصب 9 تا خطا توی کد میده که اگر آدرس ایمیل لطف کنید براتون ارسال میکنم 
شما پلاگین دیگه ای برای فروشگاه ندارید؟ مثلا متدهای ارسال که توی تیتر همین صفحه هست یا تاریخ شمسی
بازم ممنونم از اینکه نتیجه زحمات خودتون رو به اشتراک میگذارین
